# Generated by Django 5.2.3 on 2025-06-23 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Disciplina')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código da Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título da Pergunta')),
                ('content', models.TextField(help_text='Detalhe sua dúvida ou o que você procura.', verbose_name='Conteúdo da Pergunta')),
                ('file_attachment', models.FileField(blank=True, help_text='Anexe provas anteriores, enunciados, imagens, etc.', null=True, upload_to='question_attachments/', verbose_name='Anexo (Opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('answered', 'Respondida'), ('closed', 'Fechada')], default='open', max_length=10, verbose_name='Status')),
                ('is_public', models.BooleanField(default=True, verbose_name='Pública')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_asked', to='cadastro.person', verbose_name='Autor')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo da Resposta')),
                ('file_attachment', models.FileField(blank=True, help_text='Anexe gabaritos, resoluções detalhadas, etc.', null=True, upload_to='answer_attachments/', verbose_name='Anexo (Opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('is_best_answer', models.BooleanField(default=False, verbose_name='Melhor Resposta')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_provided', to='cadastro.person', verbose_name='Autor')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['created_at'],
            },
        ),
    ]
