# Generated by Django 5.2.3 on 2025-06-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='icon',
            field=models.CharField(blank=True, default='<i class="fa-solid fa-circle"></i>', null=True, verbose_name='Ícone'),
        ),
    ]
