# Generated by Django 5.2.3 on 2025-06-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='icon',
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, default='<i class="fa-solid fa-circle"></i>', null=True, verbose_name='Ícone'),
        ),
    ]
