# Generated by Django 5.2.3 on 2025-06-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nome completo da pessoa.', max_length=200, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(blank=True, help_text='Data de nascimento da pessoa.', null=True, verbose_name='Data de Nascimento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, null=True, verbose_name='Gênero')),
                ('enrollment_number', models.CharField(blank=True, help_text='Número de matrícula do estudante na UFT.', max_length=50, null=True, unique=True, verbose_name='Número de Matrícula (UFT)')),
                ('bio', models.TextField(blank=True, help_text='Uma breve descrição sobre a pessoa.', null=True, verbose_name='Biografia')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Foto de Perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['full_name'],
            },
        ),
    ]
