# Generated by Django 5.2.3 on 2025-06-23 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='enrolled_subjects',
            field=models.ManyToManyField(blank=True, related_name='students_enrolled', to='questions.subject', verbose_name='Disciplinas Cursadas'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(help_text='O usuário do sistema associado a este perfil de pessoa.', on_delete=django.db.models.deletion.CASCADE, related_name='person_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Associado'),
        ),
    ]
